# MyBatis Mapper location
mybatis:
  mapper-locations: classpath*:/db/mybatis/*Mapper.xml
spring:
  application:
    name: account-engine
  datasource:
    url: jdbc:h2:mem:testdb;mode=Postgresql
    username: sa
    password: password
    driver-class-name: org.h2.Driver

server:
  port: 8081
# Management Configuration
management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: "*"

transfer-engine:
  host: localhost
  port: 8082