#Workflow name
name: Persona Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - develop

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  DOCKER_IMAGE_TAG: dev
  DEPLOYMENT_NAME: persona

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu' # See 'Supported distributions' for available options

      # Check id develop branch
      - name: "Copy Configuration for UAT"
        run: |
          ls
          cp src/main/resources/application-uat.yaml application-uat.yaml


      - name: Build with Gradle
        run: ./gradlew build


      # Build the Docker image
      - name: Build/Publish docker image
        working-directory: ${{ env.DIR }}
        run: |
          ls -a
          docker build -t "$DOCKER_IMAGE_TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: whoami

